### ISSUE TITLE
Task Tracking

### ISSUE THREAD

**Issue by bguayante** [theturnout/court-data-pipeline#6]
- [ ] Update ontology URI in validator and SHACL file when provided path by Margaret/Stanford
- [ ] Update validator to fetch SHACL file each run to ensure parity with updates to ontology (need above URI)
- [x] Convert SPARQL query output to CSV
- [x] Add License file
- [x] Integrate pipeline modules into argparse
- [x] Merge dev and main, delete dev
